### ISSUE TITLE
Error while converting from binary to decimal.

### ISSUE THREAD

**Issue by N07070** [ZenOokami/Python-NumberConverter#1]
Hello !

I wanted to try the script, but upon converting from binary to decimal, an error showed up.

**To reproduce**:
- Run the python file,
- Choose option 2,
- Type in a binary number, for example 101 or 1 or 01001.

**Expected output**:
- A decimal number

**Actual Output**:

```
$ python NumberConverter.py 
Welcome to EoZ's number converter!
0.)Quit | 1.) Decimal to Binary | 2.) Binary to Decimal
()
Please choose option: 2
Plase input a binary number to convert: 1
Traceback (most recent call last):
  File "NumberConverter.py", line 143, in <module>
    main()
  File "NumberConverter.py", line 131, in main
    binaryDecimalMenu()
  File "NumberConverter.py", line 70, in binaryDecimalMenu
    for item in number:
TypeError: 'int' object is not iterable
```

**Comment by ZenOokami** [comment]
Hello, Sorry for the long overdue reply -- was finishing up finals and etc. - anywho, I've tried to recreate the issue, and it worked on my end. It's possible that you ran an incomplete version of the program and I probably pushed an update since then.

If the problem persists, please let me know :)
![screenshot 2015-05-13 23 48 05](https://cloud.githubusercontent.com/assets/2906275/7625804/8ec59ba6-f9ca-11e4-9ee5-f62773c50f72.png)

**Comment by ZenOokami** [comment]
My apologies! I just realized, I've only updated the file over on our group account: [link to the project](https://github.com/EssenceOfZen/Python-NumberConverter/blob/master/NumberConverter.py)
